### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by kvasbo** [ilpaolino/homeylocalapi#4]
There is a memory leak somewhere. I have a local api card set up that is polled every 15s. It just returns a few values for usage in another system. 

It was activated two days ago, and you can see the effect on memory usage in the screen shot. 

<img width="816" alt="Skjermbilde 2023-03-31 kl  08 29 37" src="https://user-images.githubusercontent.com/359896/229041348-d2f684c3-a7cf-45c9-943d-ae5a59f356c0.png">

<img width="815" alt="Skjermbilde 2023-03-31 kl  08 30 54" src="https://user-images.githubusercontent.com/359896/229041364-b7265051-668e-4f49-9c3b-09748dadc623.png">

**Comment by ilpaolino** [comment]
Hi @kvasbo 
thanks for the report.

In the chart there are 2 fall in the memory usage: have you performed a manual (or automatic) reboot or it has free up memory by itself?

**Comment by kvasbo** [comment]
It stopped and I manually restarted it.

fre. 31. mar. 2023 kl. 08:50 skrev Paolo Dadda ***@***.***>:

**Comment by ilpaolino** [comment]
We're investigating this issue here:
https://community.homey.app/t/app-pro-local-api/70840/46

Now I can only suggest you to set a timer that restart the localAPI app.

At the moment we have not yet identified the problem, if in the next few days you find any other information that can help solve the problem, I ask you to please share it, any help is appreciated.

Thank you

**Comment by kvasbo** [comment]
Cool - I have also forked the app and I'm looking to see if I can find it
myself :)

fre. 31. mar. 2023 kl. 09:01 skrev Paolo Dadda ***@***.***>:

**Comment by ilpaolino** [comment]
Hi @kvasbo , can you check if the new version has already that issue?

**Comment by kvasbo** [comment]
It works now!

tir. 11. apr. 2023 kl. 13:58 skrev Paolo Dadda ***@***.***>:
